---
name: vpn

features:
  converge_variables: true

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

instance_groups:
- name: server
  instances: 1
  jobs:
  - name: openvpn
    release: openvpn
    properties:
      server: ((virtual_network.start_ip)) ((virtual_network.netmask))
      tls_server: ((server_tls))
      dh_pem: ((dh_pem))
  - name: bosh-dns
    release: bosh-dns
    properties:
      address: ((virtual_network.server_ip))
      cache:
        enabled: true
      health:
        enabled: true
        server:
          tls: ((/dns_healthcheck_server_tls))
        client:
          tls: ((/dns_healthcheck_client_tls))
      api:
        server:
          tls: ((/dns_api_server_tls))
        client:
          tls: ((/dns_api_client_tls))
  networks:
  - name: default
    default: [dns, gateway]
  - name: elastic-ips
    static_ips: [((vpn_ip_from_bbl))]
  stemcell: xenial
  vm_type: default
  azs: [z1]

variables:
- name: server_tls
  type: certificate
  options:
    ca: /root_ca
    common_name: VPN server tls
    alternative_names:
    - vpn.((system_domain))
    key_usage:
    - digital_signature
    - key_agreement
    - key_encipherment
    extended_key_usage:
    - server_auth
- name: client_tls
  type: certificate
  options:
    ca: /root_ca
    common_name: VPN client TLS
    key_usage:
    - digital_signature
    - key_agreement
    extended_key_usage:
    - client_auth

stemcells:
- alias: xenial
  os: ubuntu-xenial
  version: latest

releases:
- name: "openvpn"
  version: "5.0.0"
  url: "https://bosh.io/d/github.com/dpb587/openvpn-bosh-release?v=5.0.0"
  sha1: "0b08f569dc18b042845897a0490d541f96f96951"
- name: "bosh-dns"
  version: "1.10.0"
  url: "https://bosh.io/d/github.com/cloudfoundry/bosh-dns-release?v=1.10.0"
  sha1: "d1aadbda5d60c44dec4a429cda872cf64f6d8d0b"
