---
name: vpn

features:
  converge_variables: true

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

instance_groups:
- name: server
  instances: 1
  jobs:
  - name: openvpn
    release: openvpn
    properties:
      server: ((virtual_network.start_ip)) ((virtual_network.netmask))
      tls_server: ((server_tls))
      dh_pem: ((dh_pem))
      push_routes:
      - "10.0.0.0 255.255.255.0"
      ccd:
      - ["((ccd.static_ip_0.common_name))", "ifconfig-push ((ccd.static_ip_0.ip)) ((virtual_network.netmask))"]
  networks:
  - name: default
    default: [dns, gateway]
  - name: elastic-ips
    static_ips: [((vpn_ip_from_bbl))]
  stemcell: xenial
  vm_type: default
  azs: [z1]

variables:
- name: server_tls
  type: certificate
  options:
    ca: /root_ca
    common_name: VPN server tls
    alternative_names:
    - vpn.((system_domain))
    key_usage:
    - digital_signature
    - key_agreement
    - key_encipherment
    extended_key_usage:
    - server_auth
- name: client_tls
  type: certificate
  options:
    ca: /root_ca
    common_name: VPN client TLS
    key_usage:
    - digital_signature
    - key_agreement
    extended_key_usage:
    - client_auth

stemcells:
- alias: xenial
  os: ubuntu-xenial
  version: latest

releases:
- name: "openvpn"
  version: "5.0.0"
  url: "https://bosh.io/d/github.com/dpb587/openvpn-bosh-release?v=5.0.0"
  sha1: "0b08f569dc18b042845897a0490d541f96f96951"
