---
name: ((deployment_name))

features:
  converge_variables: true

releases:
- name: concourse
  version: ((concourse_version))
  sha1: ((concourse_sha1))
  url: https://bosh.io/d/github.com/concourse/concourse?v=((concourse_version))
- name: garden-runc
  version: ((garden_runc_version))
  sha1: ((garden_runc_sha1))
  url: https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=((garden_runc_version))
- name: postgres
  version: ((postgres_version))
  sha1: ((postgres_sha1))
  url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=((postgres_version))

instance_groups:
- name: lite
  instances: 1
  azs: [z1]
  networks:
  - name: default
    default: [dns, gateway]
  - name: elastic-ips
    static_ips: [((public_ip))]
  stemcell: xenial
  vm_type: ((vm_type))
  persistent_disk_type: ((persistent_disk_type))
  jobs:
  - release: concourse
    name: atc
    properties:
      log_level: debug

      token_signing_key: ((token_signing_key))

      external_url: ((external_url))
      tls_bind_port: 443
      tls_cert: ((atc_tls.certificate))
      tls_key: ((atc_tls.private_key))

      github_auth:
        client_id: ((github_oauth.username))
        client_secret: ((github_oauth.password))

      main_team:
        auth:
          github:
            users:
            - ships

      add_local_users:
      - 'admin:((admin_user.password))'

      postgresql:
        database: &db_name atc
        role: &db_role
          name: concourse
          password: ((postgres_password))

  - release: concourse
    name: tsa
    properties:
      log_level: debug
      host_key: ((tsa_host_key))
      token_signing_key: ((token_signing_key))
      authorized_keys: [((worker_key.public_key))]
  - release: postgres
    name: postgres
    properties:
      databases:
        port: 5432
        databases:
        - name: *db_name
        roles:
        - *db_role
  - release: concourse
    name: worker
    consumes: {baggageclaim: {from: worker-baggageclaim}}
    properties:
      drain_timeout: 10m
      tsa: {worker_key: ((worker_key))}
  - release: concourse
    name: baggageclaim
    properties: {log_level: debug}
    provides: {baggageclaim: {as: worker-baggageclaim}}
  - release: garden-runc
    name: garden
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777

variables:
- name: postgres_password
  type: password
- name: token_signing_key
  type: rsa
- name: tsa_host_key
  type: ssh
- name: worker_key
  type: ssh
- name: admin_user
  type: user
  options:
    username: admin
    length: 30
- name: atc_tls
  type: certificate
  options:
    ca: /root_ca
    common_name: ((external_host))
    alternative_names: [((external_host))]

stemcells:
- alias: xenial
  os: ubuntu-xenial
  version: latest

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
